### ISSUE TITLE
programs_decode: fix for QEMU cpio parsing can cause unathorized access

### ISSUE THREAD

**Issue by Cinek28** [phoenix-rtos/phoenix-rtos-kernel#123]
When no CPIO is linked the following instructions:

		/* Happens in QEMU when programs are not page aligned. What the hell? */
		cpio = (void *)(programs - 0x1000);

		if (hal_strncmp(cpio->c_magic, "070701", 6)) {
			lib_printf("programs: valid cpio archive not found\n");
			return -EINVAL;
		}

		lib_printf("programs: cpio archive found dislocated\n");

can cause access to unauthorized memory. For example when on armv7m7-imxrt106x there is no CPIO
under programs symbol (which is set to 0x20000000), programs-0x1000 will point to reserved memory.

**Comment by pawelpisarczyk** [comment]
I got it. I have to find the best solution how to detect that we are running inside qemu-i386

**Comment by agkaminski** [comment]
Maybe we can check if this address is valid instead? Should be easy enough, just compare it with kernel mmap boundaries.

**Comment by pawelpisarczyk** [comment]
I think that better idea is to check if the final cpio archive address fits into the data segment (defined by _data prefixed symbols), but the best solution is to check that we are running inside the broken qemu.

**Comment by pawelpisarczyk** [comment]
I solved this by adding implicit check of HAL name before changing programs pointer to check if CPIO archive is not dislocated by incorrect kernel file loading performed by qemu-system-i386 emulator.
