### ISSUE TITLE
riscv64: Adding support for latest qemu.

### ISSUE THREAD

**Issue by pawelpisarczyk** [phoenix-rtos/phoenix-rtos-kernel#133]
Unfortunately, on the newest qemu-system-riscv64 system is unable to boot. It can be caused by adding to qemu support for OpenSBI. Some investigation should be done.

**Comment by pawelpisarczyk** [comment]
Łukasz,

Could you close this issue?

PP

**Comment by Maxez** [comment]
> 
> 
> Łukasz,
> 
> Could you close this issue?
> 
> PP

I don't have permissions to close the issue.

**Comment by pawelpisarczyk** [comment]
SOlved
