### ISSUE TITLE
ia32: Adding APIC support to handle properly interrupt redistribution on SMP architectures.

### ISSUE THREAD

**Issue by pawelpisarczyk** [phoenix-rtos/phoenix-rtos-kernel#134]

**Comment by badochov** [comment]
@agkaminski  @astalke  can this be closed now?

**Comment by agkaminski** [comment]
Done in https://github.com/phoenix-rtos/phoenix-rtos-kernel/commit/39b0e4e92951f772f3566ce4cef2966a129bc0b3
