### ISSUE TITLE
HAL: armv7m: Missing break

### ISSUE THREAD

**Issue by nalajcie** [phoenix-rtos/phoenix-rtos-kernel#172]
Missing break in switch-case:

https://github.com/phoenix-rtos/phoenix-rtos-kernel/blob/f84dea0c56a9743e9b9825911aff836a8b4f3c81/hal/armv7m/imxrt/10xx/imxrt10xx.c#L214-L218

Found while toying with sonarscanner software (https://sonarcloud.io/project/issues?id=nalajcie_phoenix-rtos-project&issues=AXcHQntzk8qWjK72eCGK&open=AXcHQntzk8qWjK72eCGK).

Might affect also other archs.

**Comment by agkaminski** [comment]
Fixed in 3b8c586eb338b5562ee9a66ca9defbd1351c51d7. Thank you.
