### ISSUE TITLE
Checking if namelen is negative in posix_gethostname() and posix_sethostname() functions

### ISSUE THREAD

**Issue by kemonats** [phoenix-rtos/phoenix-rtos-kernel#207]
Is it really necessary to check `namelen < 0` in `posix_gethostname()` and `posix_sethostname()` functions, if `namelen` is of type `size_t` and will never be `< 0`.
The compiler skips this condition.

**Comment by ziemleszcz** [comment]
Nope, I was falsely inspired by gethostname man page.

**Comment by agkaminski** [comment]
Fixed in https://github.com/phoenix-rtos/phoenix-rtos-kernel/commit/a1d44c4c2c3dd5600fcd655cce8da653572c8fd0 (never got broken too)
