### ISSUE TITLE
Functions exit and sleep hang the shell prompt when called from a multithreaded application

### ISSUE THREAD

**Issue by Maxez** [phoenix-rtos/phoenix-rtos-kernel#56]
Steps to reproduce:
1. Call exit(1) or sleep(5) in the main thread of a multithreaded application after some worker threads have already started (I used test_malloc from libphoenix for testing).
2. The shell prompt (from which the application was started) hangs.

Problem detected on ia32 and confirmed on arm-imx6ull.

**Comment by js6i** [comment]
Should be fixed by 25b2194401ea50eb7b5c5cf046a619b73cb788c3 on ia32

**Comment by js6i** [comment]
Should be fixed further by e95582bc5114744084c8ed01b37366ac559d2a9c
